### ISSUE TITLE
oAuth RSA Signature encoding issue

### ISSUE THREAD

**Issue by MikeyF-Anovia** [MasterCard/mastercard-api-node#13]
Hi. Documentation at 
https://developer.mastercard.com/portal/display/api/MATCH+-+Sample+Code 
claims that the signature needs to have several characters url encoded. 
   replace "+" with "%20"
   replace "*" with "%2A"
   replace "%7E" with "~"

But the _signAndMakeRequest function in this SDK replaces ~ with %7E rather than replacing %7E with ~
  oauthParms.signature = oauthParms.signature.replace('+','%20');
  oauthParms.signature = oauthParms.signature.replace('*','%2A');
  oauthParms.signature = oauthParms.signature.replace('~','%7E');

It would seem that either the SDK is incorrect or information at https://developer.mastercard.com/portal/display/api/MATCH+-+Sample+Code is incorrect. 

Even after I reverse the parameters to match what the documentations claims, I am still getting the error: The request contains an incomplete or invalid oauth_signature.

**Comment by kkrauth** [comment]
Sorry about the problems you encountered with this SDK which was admittedly pretty rough around the edges. We have a new Match SDK for node that is available in NPM:
https://www.npmjs.com/package/mastercard-match

Can you please try that one out instead? The documentation on how to use the new SDK is available on  the developer site:
https://developer.mastercard.com/documentation/match/

If you encounter any issues please don't hesitate to contact us using the form below:
https://mastercarddevelopersupport.desk.com/customer/portal/emails/new

**Comment by MikeyF-Anovia** [comment]
Thanks!
